### ISSUE TITLE
missing Potrace ?

### ISSUE THREAD

**Issue by ChameleonScales** [matze/inkscape-flatpak#1]
I just installed the flatpak from Inkscape's download page on my OpenSUSE 42.2 and it seems it didn't install the Potrace library because I don't have the "Trace Bitmap" option under Path and the context menu item doesn't do anything.
So I installed Potrace from YaST and it didn't work any better.
So I decided to install Inkscape from YaST as well (which is still at 0.91) and use the Trace Bitmap from there

But what should I do to make it work on the flatpak ?

**Comment by matze** [comment]
I will check which dependencies are required to make potrace available with the Flatpak. I don't know the internal structure of Inkscape that well but I suppose it's checking and calling an external binary which you just cannot do from a sandboxed application, hence you don't see anything when installing potrace with YaST.

**Comment by ChameleonScales** [comment]
Thanks ! It works now.
