### ISSUE TITLE
lxml needed for some extensions to work

### ISSUE THREAD

**Issue by lilic** [matze/inkscape-flatpak#2]
For the`Extensions -> Visualize Path -> Draw Handles`, and this is the case for some other extensions as well, to work you need lxml. The gnome runtime does not provide that, so you would need to add [python-lxml](https://github.com/lxml/lxml).

**Comment by matze** [comment]
Thanks for the report. This might take a while to get sorted out, so far I only had to declary C/C++ dependencies …
