### ISSUE TITLE
Missing PDF support

### ISSUE THREAD

**Issue by skierpage** [matze/inkscape-flatpak#4]
I'm not sure if you built it using this recipe, but https://inkscape.org/en/~matze/%E2%98%85inkscapeflatpak does not seem to support opening a PDF. Maybe it needs to include the Poppler library?

**Comment by matze** [comment]
Thanks for the report. I will try to sort it out ASAP.

And yes, this repo contains the recipe for the Flatpak bundle distributed via the Inkscape webpage. An almost identical copy is available through Flathub though.
